# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de251de9ac9889592da13c725b740c14039cee21d1879adf28a31e6d479565ff4f78ffde85f69e86ce15ff3343a78e468ead6efb564ba042ac9d60da87dd8e65

test:
  secret_key_base: 85be6a79bf37c697a0de01bd2ee66e49532bd477daafd1911bddc5940f9ed1372108d928b1c9ecce81821acd968aa8586462b0eeb651b9137b6607e539844954

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
